services:
  bot:
    image: "jangodar/tg_bot_1:ubuntu"
    restart: "unless-stopped"
    environment:
      - BOT_TOKEN=6894820119:AAF2RLqBpsPCCgZ09pleLFFa0rAfrXTNG7s
      - REDIS_DSN=redis://redis_fsm
  
  redis_fsm:
    image: "redis:7"
    restart: "unless-stopped"
    volumes: 
      - "/home/ubuntu/redis/redis.conf:/usr/local/etc/redis/redis.conf"
      - "/home/ubuntu/redis/data:/data"
    command: "redis-server /usr/local/etc/redis/redis.conf"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]